// Gujarat Sultanate Historical Events Dataset (1391 – 1592 CE)
// All historical data extracted verbatim from authoritative chronicles (including Mirat-i-Sikandari)

const GUJARAT_SULTANATE_DATA = [
  // ==========================================
  // PHASE 1: THE RISE & THE FOUNDER (1391 – 1442 CE)
  // ==========================================
  {
    id: "evt-1391",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "1391 CE",
    numericYear: 1391,
    hijri: "",
    category: "Political",
    primaryCategory: "Political",
    title: "Zafar Khan appointed Subahdar of Gujarat",
    figures: ["Zafar Khan (Wajih-ul-Mulk)", "Nasir-ud-din Muhammad Shah Tughluq III", "Farhat-ul-Mulk (Rasti Khan)"],
    details: "Sultan Nasir-ud-din Muhammad Shah Tughluq III dispatches Zafar Khan (son of Wajih-ul-Mulk, a converted Tanka Rajput from Punjab) to suppress the rebellious governor Farhat-ul-Mulk (Rasti Khan).",
    isKeyMilestone: true
  },
  {
    id: "evt-1392",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "1392 CE",
    numericYear: 1392,
    hijri: "",
    category: "Military",
    primaryCategory: "Military",
    title: "Battle of Kambhoi (near Patan)",
    figures: ["Zafar Khan", "Farhat-ul-Mulk"],
    details: "Zafar Khan decisively defeats and slays Farhat-ul-Mulk at Kambhoi. He enters Anhilwad Patan, cleanses the administrative machinery, and restores order across the Gujarat plains.",
    isKeyMilestone: false
  },
  {
    id: "evt-1392-birth",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "c. 1392–1394 CE",
    numericYear: 1393,
    hijri: "",
    category: "Dynastic",
    primaryCategory: "Dynastic",
    title: "Birth of Prince Ahmad Khan (Ahmad Shah I)",
    figures: ["Tatar Khan", "Ahmad Shah I", "Zafar Khan"],
    details: "Born to Tatar Khan (Zafar Khan's ambitious son). From infancy, he is groomed in martial arts and Islamic theology.",
    isKeyMilestone: false
  },
  {
    id: "evt-1398",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "1398 CE",
    numericYear: 1398,
    hijri: "",
    category: "Geopolitical",
    primaryCategory: "Geopolitical",
    title: "Timur's Sack of Delhi",
    figures: ["Timur (Tamerlane)", "Tughluq Dynasty"],
    details: "Timur's brutal sack of Delhi shatters the Tughluq Sultanate. Central authority collapses entirely, leaving provincial governors to chart independent courses.",
    isKeyMilestone: true
  },
  {
    id: "evt-1403",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "1403 CE",
    numericYear: 1403,
    hijri: "",
    category: "Dynastic Coup",
    primaryCategory: "Dynastic",
    title: "Tatar Khan imprisons Zafar Khan",
    figures: ["Tatar Khan (Sultan Nasir-ud-din Muhammad Shah)", "Zafar Khan"],
    details: "Impatient to seize the fallen imperial mantle, Tatar Khan deposes and imprisons his father Zafar Khan at Asawal. He proclaims himself Sultan Nasir-ud-din Muhammad Shah (the first sovereign sultan of Gujarat).",
    isKeyMilestone: false
  },
  {
    id: "evt-1404",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "1404 CE",
    numericYear: 1404,
    hijri: "",
    category: "Assassination",
    primaryCategory: "Assassination",
    title: "Death of Tatar Khan at Sinor",
    figures: ["Tatar Khan", "Shams Khan", "Zafar Khan"],
    details: "While marching toward Delhi, Tatar Khan dies suddenly at Sinor on the Narmada River—widely documented in the Mirat-i-Sikandari as poisoned by his uncle Shams Khan to rescue Zafar Khan. Zafar Khan is freed and resumes the regency.",
    isKeyMilestone: false
  },
  {
    id: "evt-1407",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "1407 CE",
    numericYear: 1407,
    hijri: "",
    category: "Independence",
    primaryCategory: "Political",
    title: "Coronation of Muzaffar Shah I at Birpur",
    figures: ["Zafar Khan (Sultan Shams-ud-din Muzaffar Shah I)"],
    details: "Urged by nobles to formalize sovereignty due to Delhi's vacuum, Zafar Khan takes royal titles as Sultan Shams-ud-din Muzaffar Shah I at Birpur. Coins are struck and the Khutba is read in his name.",
    isKeyMilestone: true
  },
  {
    id: "evt-1407-malwa",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "1407–1408 CE",
    numericYear: 1407,
    hijri: "",
    category: "Military",
    primaryCategory: "Military",
    title: "Malwa Campaign",
    figures: ["Muzaffar Shah I", "Dilawar Khan Ghori", "Alp Khan (Hushang Shah)", "Nusrat Khan"],
    details: "Muzaffar Shah invades Malwa to avenge the death of his ally Dilawar Khan Ghori. He defeats and captures Sultan Alp Khan (Hushang Shah) at Dhar, placing his brother Nusrat Khan in temporary command.",
    isKeyMilestone: false
  },
  {
    id: "evt-1410",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "1410 / Early 1411 CE",
    numericYear: 1410,
    hijri: "",
    category: "Dynastic",
    primaryCategory: "Dynastic",
    title: "Death of Muzaffar Shah I",
    figures: ["Muzaffar Shah I", "Ahmad Shah I"],
    details: "Muzaffar Shah I dies at Patan (some chronicles allege he was poisoned by his grandson Ahmad; others state he succumbed to natural old age after designating Ahmad as heir).",
    isKeyMilestone: false
  },
  {
    id: "evt-1411-coronation",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "Jan / Feb 1411 CE",
    numericYear: 1411,
    hijri: "2 Dhu al-Qi'dah 813 AH",
    category: "Dynastic",
    primaryCategory: "Dynastic",
    title: "Coronation of Ahmad Shah I",
    figures: ["Ahmad Shah I"],
    details: "Ahmad Shah ascends the throne at Patan at approximately 19–20 years of age.",
    isKeyMilestone: true
  },
  {
    id: "evt-1411-foundation",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "Feb 26, 1411 CE",
    numericYear: 1411,
    hijri: "2 Dhu al-Qi'dah 813 AH",
    category: "Architectural / Spiritual",
    primaryCategory: "Architectural",
    title: "Foundation of Ahmedabad",
    figures: ["Ahmad Shah I", "Shaikh Ahmad Khattu Ganj Bakhsh", "Kazi Ahmad", "Malik Ahmad"],
    details: "Ahmad Shah shifts the capital south from Patan to the banks of the Sabarmati River near the ancient hamlet of Asawal. Guided by Sufi saint Shaikh Ahmad Khattu Ganj Bakhsh, the foundation is consecrated by four revered men named Ahmad: the Sultan, Shaikh Ahmad Khattu, Kazi Ahmad, and Malik Ahmad.",
    isKeyMilestone: true
  },
  {
    id: "evt-1411-bhadra",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "1411–1414 CE",
    numericYear: 1411,
    hijri: "",
    category: "Architectural",
    primaryCategory: "Architectural",
    title: "Construction of the Citadel (Bhadra Fort) & Early Mosques",
    figures: ["Ahmad Shah I"],
    details: "Rapid construction of the red sandstone Bhadra Fort, the city's processional gateway (Teen Darwaza), and Ahmad Shah's Citadel Mosque (completed in 1414 CE for the private use of the royal household).",
    isKeyMilestone: false
  },
  {
    id: "evt-1414",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "1414–1416 CE",
    numericYear: 1414,
    hijri: "",
    category: "Military / Family",
    primaryCategory: "Military",
    title: "Rebellion of Uncles & Subjugation of Sorath",
    figures: ["Ahmad Shah I", "Firuz Khan", "Haibat Khan", "Rao Khengara (Mandalik)"],
    details: "Ahmad Shah crushes an internal rebellion led by his cousins and uncles (Firuz Khan and Haibat Khan). He then marches into Saurashtra, besieges Junagadh, and extracts tribute from Chudasama ruler Rao Khengara (Mandalik).",
    isKeyMilestone: false
  },
  {
    id: "evt-1416",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "c. 1416–1420 CE",
    numericYear: 1416,
    hijri: "",
    category: "Dynastic / Marriage",
    primaryCategory: "Dynastic",
    title: "Rajput Marital Alliances",
    figures: ["Ahmad Shah I", "Lala Baghela", "Rulers of Jhalawar"],
    details: "Ahmad Shah consolidates Gujarat's borders by taking Rajput princesses into the imperial zenana, most notably contracting alliances with the Baghela house of Dholka (Lala Baghela) and the rulers of Jhalawar.",
    isKeyMilestone: false
  },
  {
    id: "evt-1417",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "1417–1422 CE",
    numericYear: 1417,
    hijri: "",
    category: "Military",
    primaryCategory: "Military",
    title: "Border Wars with Malwa & Khandesh",
    figures: ["Ahmad Shah I", "Sultan Hushang Shah of Malwa", "Nasir Khan of Khandesh"],
    details: "Repeated campaigns against Sultan Hushang Shah of Malwa and Nasir Khan of Khandesh, who repeatedly attempt to destabilize the eastern borders of Gujarat.",
    isKeyMilestone: false
  },
  {
    id: "evt-1424",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "1424 CE",
    numericYear: 1424,
    hijri: "827 AH",
    category: "Architectural",
    primaryCategory: "Architectural",
    title: "Consecration of the Jami Masjid of Ahmedabad",
    figures: ["Ahmad Shah I"],
    details: "Ahmad Shah finishes his architectural masterpiece: the grand Friday Mosque (Jami Masjid) featuring 260 carved columns, 15 domes, and intricate stone jali work blending Hindu-Jain artisanal stonework with Indo-Islamic design.",
    isKeyMilestone: true
  },
  {
    id: "evt-1426",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "1426 CE",
    numericYear: 1426,
    hijri: "",
    category: "Military / Architectural",
    primaryCategory: "Architectural",
    title: "Founding of Ahmadnagar (Himmatnagar)",
    figures: ["Ahmad Shah I", "Rao of Idar"],
    details: "Ahmad Shah establishes the fortified garrison city of Ahmadnagar on the Hathmati River to permanently check the raids of the Rajput Rao of Idar.",
    isKeyMilestone: false
  },
  {
    id: "evt-1429",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "1429–1431 CE",
    numericYear: 1429,
    hijri: "",
    category: "Military",
    primaryCategory: "Military",
    title: "Clashes with the Bahmani Sultanate",
    figures: ["Ahmad Shah I", "Ahmad Shah Bahmani"],
    details: "Conflict breaks out with Ahmad Shah Bahmani over the offshore island of Mahim (modern-day Mumbai) and the border district of Baglan; Ahmad Shah's navy and ground forces successfully secure the northern Konkan coastline.",
    isKeyMilestone: false
  },
  {
    id: "evt-1442",
    phaseId: 1,
    phaseTitle: "Phase 1: The Rise & The Founder (1391 – 1442 CE)",
    phaseShort: "Phase 1: The Rise",
    year: "1442 CE",
    numericYear: 1442,
    hijri: "4 Rabi' al-Awwal 846 AH",
    category: "Dynastic",
    primaryCategory: "Dynastic",
    title: "Death of Ahmad Shah I",
    figures: ["Ahmad Shah I"],
    details: "Ahmad Shah dies at age 51 after a 31-year reign. He is interred in the grand domed mausoleum (Hazira / Badshah no Hajiro) adjacent to the Jami Masjid in Ahmedabad.",
    isKeyMilestone: true
  },

  // ==========================================
  // PHASE 2: PALACE INTRIGUE & SURVIVAL (1442 – 1458 CE)
  // ==========================================
  {
    id: "evt-1442-accession",
    phaseId: 2,
    phaseTitle: "Phase 2: Palace Intrigue & Survival (1442 – 1458 CE)",
    phaseShort: "Phase 2: Palace Intrigue",
    year: "1442 CE",
    numericYear: 1442,
    hijri: "",
    category: "Dynastic",
    primaryCategory: "Dynastic",
    title: "Accession of Muhammad Shah II (Zar-Baksh)",
    figures: ["Ghiyas-ud-din Muhammad Shah II"],
    details: "Ghiyas-ud-din Muhammad Shah II (son of Ahmad Shah I) ascends the throne. Famed for his open-handed generosity with court wealth, earning the moniker Zar-Baksh ('The Gold Giver').",
    isKeyMilestone: false
  },
  {
    id: "evt-1445-khattu",
    phaseId: 2,
    phaseTitle: "Phase 2: Palace Intrigue & Survival (1442 – 1458 CE)",
    phaseShort: "Phase 2: Palace Intrigue",
    year: "May 1445 CE",
    numericYear: 1445,
    hijri: "14 Shawwal 849 AH",
    category: "Spiritual",
    primaryCategory: "Spiritual",
    title: "Death of Shaikh Ahmad Khattu Ganj Bakhsh",
    figures: ["Shaikh Ahmad Khattu Ganj Bakhsh", "Muhammad Shah II"],
    details: "The spiritual patron of Ahmedabad dies at his hermitage in Sarkhej at an advanced age. Muhammad Shah II immediately commissions a tomb complex in his honor.",
    isKeyMilestone: false
  },
  {
    id: "evt-1445-birth-fateh",
    phaseId: 2,
    phaseTitle: "Phase 2: Palace Intrigue & Survival (1442 – 1458 CE)",
    phaseShort: "Phase 2: Palace Intrigue",
    year: "Nov 1445 CE",
    numericYear: 1445,
    hijri: "849 AH",
    category: "Dynastic",
    primaryCategory: "Dynastic",
    title: "Birth of Prince Fateh Khan (Mahmud Begada)",
    figures: ["Fateh Khan (Mahmud Begada)", "Muhammad Shah II", "Bibi Mughli", "Jam Junan (Samma dynasty)"],
    details: "Born to Muhammad Shah II and his chief consort, Bibi Mughli (daughter of Jam Junan, ruler of the Samma dynasty of Sindh).",
    isKeyMilestone: true
  },
  {
    id: "evt-1446-sarkhej",
    phaseId: 2,
    phaseTitle: "Phase 2: Palace Intrigue & Survival (1442 – 1458 CE)",
    phaseShort: "Phase 2: Palace Intrigue",
    year: "1446–1450 CE",
    numericYear: 1446,
    hijri: "",
    category: "Architectural",
    primaryCategory: "Architectural",
    title: "Construction of Sarkhej Roza",
    figures: ["Shaikh Ahmad Khattu", "Muhammad Shah II"],
    details: "Active construction of the Sufi shrine, central mosque, and surrounding pavillons at Sarkhej to house Shaikh Ahmad Khattu's tomb.",
    isKeyMilestone: false
  },
  {
    id: "evt-1451-death-muh2",
    phaseId: 2,
    phaseTitle: "Phase 2: Palace Intrigue & Survival (1442 – 1458 CE)",
    phaseShort: "Phase 2: Palace Intrigue",
    year: "Feb 1451 CE",
    numericYear: 1451,
    hijri: "855 AH",
    category: "Dynastic / Military",
    primaryCategory: "Dynastic",
    title: "Death of Muhammad Shah II",
    figures: ["Muhammad Shah II", "Rana Kumbha of Mewar", "Rawal of Champaner"],
    details: "Muhammad Shah II falls ill and dies at Godhra during a retreat from military campaigns against Rana Kumbha of Mewar and the Rawal of Champaner (contemporary accounts suspect poison administered by conspirators).",
    isKeyMilestone: false
  },
  {
    id: "evt-1451-accession-qutb",
    phaseId: 2,
    phaseTitle: "Phase 2: Palace Intrigue & Survival (1442 – 1458 CE)",
    phaseShort: "Phase 2: Palace Intrigue",
    year: "Feb 1451 CE",
    numericYear: 1451,
    hijri: "",
    category: "Dynastic",
    primaryCategory: "Dynastic",
    title: "Accession of Qutb-ud-din Ahmad Shah II",
    figures: ["Qutb-ud-din Ahmad Shah II (Jalal Khan)", "Fateh Khan"],
    details: "Jalal Khan, another son of Muhammad Shah II, ascends as Qutb-ud-din Ahmad Shah II, bypassing the child Fateh Khan.",
    isKeyMilestone: false
  },
  {
    id: "evt-1451-kapadvanj",
    phaseId: 2,
    phaseTitle: "Phase 2: Palace Intrigue & Survival (1442 – 1458 CE)",
    phaseShort: "Phase 2: Palace Intrigue",
    year: "1451 CE",
    numericYear: 1451,
    hijri: "",
    category: "Military",
    primaryCategory: "Military",
    title: "Battle of Kapadvanj",
    figures: ["Qutb-ud-din Ahmad Shah II", "Sultan Mahmud Khalji of Malwa"],
    details: "Sultan Mahmud Khalji of Malwa invades deep into Gujarat to exploit the royal succession. Qutb-ud-din meets him at Kapadvanj and wins an engagement, securing his throne.",
    isKeyMilestone: false
  },
  {
    id: "evt-1451-kankaria",
    phaseId: 2,
    phaseTitle: "Phase 2: Palace Intrigue & Survival (1442 – 1458 CE)",
    phaseShort: "Phase 2: Palace Intrigue",
    year: "1451–1453 CE",
    numericYear: 1451,
    hijri: "",
    category: "Architectural",
    primaryCategory: "Architectural",
    title: "Excavation of Hauz-i-Qutb (Kankaria Lake)",
    figures: ["Qutb-ud-din Ahmad Shah II"],
    details: "Qutb-ud-din completes the vast 34-sided polygon reservoir (Kankaria Lake) along with the central summer palace and garden island known as Nagina Wadi (Bagh-i-Nagina). Sarkhej's central tomb is also finished.",
    isKeyMilestone: true
  },
  {
    id: "evt-1451-harem-war",
    phaseId: 2,
    phaseTitle: "Phase 2: Palace Intrigue & Survival (1442 – 1458 CE)",
    phaseShort: "Phase 2: Palace Intrigue",
    year: "1451–1458 CE",
    numericYear: 1451,
    hijri: "",
    category: "Dynastic Intrigue",
    primaryCategory: "Dynastic",
    title: "The Harem Cold War & Hazrat Shah Alam's Intervention",
    figures: ["Prince Fateh Khan", "Qutb-ud-din Ahmad Shah II", "Bibi Mughli", "Hazrat Shah Alam (Syed Sirajuddin Muhammad Bukhari)"],
    details: "Paranoid of young Prince Fateh Khan's popularity, Qutb-ud-din repeatedly attempts to seize or assassinate his half-brother. Bibi Mughli removes Fateh Khan from the palace and places him under the spiritual protection of the Bukhari Sufi saint Hazrat Shah Alam (Syed Sirajuddin Muhammad Bukhari). Following the death of her sister, Bibi Mughli marries Shah Alam, securing the political backing of Gujarat's religious elite for Fateh Khan.",
    isKeyMilestone: true
  },
  {
    id: "evt-1458-death-qutb",
    phaseId: 2,
    phaseTitle: "Phase 2: Palace Intrigue & Survival (1442 – 1458 CE)",
    phaseShort: "Phase 2: Palace Intrigue",
    year: "May 1458 CE",
    numericYear: 1458,
    hijri: "Rajab 862 AH",
    category: "Dynastic",
    primaryCategory: "Dynastic",
    title: "Death of Qutb-ud-din Ahmad Shah II",
    figures: ["Qutb-ud-din Ahmad Shah II"],
    details: "Qutb-ud-din dies suddenly at age 23. Chroniclers state he was wounded by his own sword after falling from an enraged war elephant, though court rumors pointed to slow poison.",
    isKeyMilestone: false
  },
  {
    id: "evt-1458-daud-khan",
    phaseId: 2,
    phaseTitle: "Phase 2: Palace Intrigue & Survival (1442 – 1458 CE)",
    phaseShort: "Phase 2: Palace Intrigue",
    year: "May 1458 CE",
    numericYear: 1458,
    hijri: "",
    category: "Dynastic Coup",
    primaryCategory: "Dynastic",
    title: "The 27-Day Reign of Daud Khan",
    figures: ["Daud Khan", "Imad-ul-Mulk"],
    details: "Court nobles install Daud Khan (uncle of Qutb-ud-din). Daud alienates the nobility through incompetence, elevating common servants and mismanaging treasury funds. The grand vizier Imad-ul-Mulk deposes him after exactly 27 days.",
    isKeyMilestone: false
  },
  {
    id: "evt-1458-coronation-begada",
    phaseId: 2,
    phaseTitle: "Phase 2: Palace Intrigue & Survival (1442 – 1458 CE)",
    phaseShort: "Phase 2: Palace Intrigue",
    year: "June 1458 CE",
    numericYear: 1458,
    hijri: "1 Sha'ban 862 AH",
    category: "Dynastic",
    primaryCategory: "Dynastic",
    title: "Coronation of Mahmud Begada",
    figures: ["Sultan Nasir-ud-din Mahmud Shah I (Fateh Khan / Mahmud Begada)", "Hazrat Shah Alam"],
    details: "13-year-old Prince Fateh Khan is escorted from Hazrat Shah Alam's sanctuary to the Bhadra Fort and crowned as Sultan Nasir-ud-din Mahmud Shah I.",
    isKeyMilestone: true
  },

  // ==========================================
  // PHASE 3: THE GOLDEN AGE – MAHMUD BEGADA (1458 – 1511 CE)
  // ==========================================
  {
    id: "evt-1459-conspiracy",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "1459 CE",
    numericYear: 1459,
    hijri: "",
    category: "Political",
    primaryCategory: "Political",
    title: "Suppression of the Nobility's Conspiracy",
    figures: ["Mahmud Begada"],
    details: "Just months into his reign, senior ministers conspire to depose Mahmud. The 13-year-old sultan exposes the treason, summons his royal bodyguard, and personally leads his forces out of the Bhadra gates to scatter the rebels.",
    isKeyMilestone: false
  },
  {
    id: "evt-1460s-persona",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "c. 1460s CE",
    numericYear: 1465,
    hijri: "",
    category: "Cultural / Personal",
    primaryCategory: "Cultural",
    title: "Emergence of the 'Begada' Persona",
    figures: ["Mahmud Begada"],
    details: "Mahmud develops his physical regimen: consuming extraordinary amounts of food daily, wearing an enormous upturned moustachio, and ingesting small quantities of poison daily to build biological immunity against assassination.",
    isKeyMilestone: true
  },
  {
    id: "evt-1467-uparkot",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "1467–1469 CE",
    numericYear: 1467,
    hijri: "",
    category: "Military",
    primaryCategory: "Military",
    title: "Initial Sieges of Uparkot (Junagadh)",
    figures: ["Mahmud Begada", "Rao Mandalik IV (Chudasama)"],
    details: "Begada launches coordinated assaults against the Chudasama stronghold of Girnar/Junagadh. Rao Mandalik IV holds the mountain fortress, but his supplies are progressively choked off.",
    isKeyMilestone: false
  },
  {
    id: "evt-1470-junagadh",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "Dec 1470 CE",
    numericYear: 1470,
    hijri: "",
    category: "Military / Political",
    primaryCategory: "Military",
    title: "Fall of Junagadh (The First 'Gadh')",
    figures: ["Mahmud Begada", "Rao Mandalik IV"],
    details: "Rao Mandalik IV surrenders Junagadh to Begada. The Rao converts to Islam, is granted royal lands, and spends his final days at court. Junagadh is rebuilt as a secondary capital and renamed Mustafabad.",
    isKeyMilestone: true
  },
  {
    id: "evt-1472-piracy",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "1472 CE",
    numericYear: 1472,
    hijri: "",
    category: "Military",
    primaryCategory: "Military",
    title: "Suppression of Kutch, Sindh, and Dwarka Piracy",
    figures: ["Mahmud Begada"],
    details: "Begada leads campaigns across the Rann of Kutch into lower Sindh to subdue nomadic raiders, followed by a punitive expedition to Bet Shankhodhar (Dwarka) to eradicate pirate fleets terrorizing Arabian Sea trade.",
    isKeyMilestone: false
  },
  {
    id: "evt-1475-shah-alam",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "1475 CE",
    numericYear: 1475,
    hijri: "17 Jumada II 880 AH",
    category: "Spiritual",
    primaryCategory: "Spiritual",
    title: "Death of Hazrat Shah Alam",
    figures: ["Hazrat Shah Alam", "Mahmud Begada"],
    details: "The Bukhari saint passes away. Begada and his courtiers commission the mausoleum and mosque complex at Rasulabad (Shah Alam no Rozo).",
    isKeyMilestone: false
  },
  {
    id: "evt-1482-prelude-pavagadh",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "1482 CE",
    numericYear: 1482,
    hijri: "",
    category: "Military",
    primaryCategory: "Military",
    title: "Prelude to Pavagadh",
    figures: ["Malik Asad", "Rawal Patai (Jaisinh / Jaysinhadeva)", "Mahmud Begada"],
    details: "Malik Asad, Begada's border commander, is attacked by Rawal Patai (Jaisinh / Jaysinhadeva) of Champaner. Begada uses the skirmish to launch an all-out assault against the hill fortress.",
    isKeyMilestone: false
  },
  {
    id: "evt-1482-siege-pavagadh",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "1482–1484 CE",
    numericYear: 1482,
    hijri: "",
    category: "Military",
    primaryCategory: "Military",
    title: "The 20-Month Siege of Pavagadh",
    figures: ["Mahmud Begada", "Rawal Patai"],
    details: "Begada besieges the ancient fortress of Pavagadh. Rawal Patai mounts a desperate defense from the upper citadel, but breaches are blown in the outer walls in late 1484.",
    isKeyMilestone: false
  },
  {
    id: "evt-1484-fall-pavagadh",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "Nov 1484 CE",
    numericYear: 1484,
    hijri: "889 AH",
    category: "Military / Geopolitical",
    primaryCategory: "Military",
    title: "Fall of Pavagadh (The Second 'Gadh')",
    figures: ["Mahmud Begada", "Rawal Patai"],
    details: "Pavagadh falls; Rawal Patai is captured and executed after refusing to convert. Securing both Girnar and Pavagadh cements the Sultan's historical moniker: Be-Gadh ('Lord of Two Forts' / Begada).",
    isKeyMilestone: true
  },
  {
    id: "evt-1484-champaner",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "1484–1500 CE",
    numericYear: 1484,
    hijri: "",
    category: "Architectural",
    primaryCategory: "Architectural",
    title: "Founding of Muhammadabad (Champaner)",
    figures: ["Mahmud Begada"],
    details: "Begada establishes Champaner at the base of Pavagadh as his principal royal residence. Construction begins on its fortified walls, palaces, stepwells, and the magnificent Jami Masjid of Champaner (renowned for its carved stone mihrabs and elevated minarets).",
    isKeyMilestone: true
  },
  {
    id: "evt-1498-vasco",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "1498 CE",
    numericYear: 1498,
    hijri: "",
    category: "Geopolitical",
    primaryCategory: "Geopolitical",
    title: "Vasco da Gama reaches Calicut",
    figures: ["Vasco da Gama", "Portuguese Crown"],
    details: "The arrival of the Portuguese establishes European naval ambition in the Indian Ocean, directly threatening Gujarat's spice trade, ports (Khambhat, Diu, Surat), and royal customs revenues.",
    isKeyMilestone: true
  },
  {
    id: "evt-1499-adalaj",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "1499 CE",
    numericYear: 1499,
    hijri: "",
    category: "Architectural",
    primaryCategory: "Architectural",
    title: "Construction of the Adalaj Stepwell",
    figures: ["Queen Rudabai", "Rana Veer Singh (Vaghela)", "Mahmud Begada"],
    details: "Built by Queen Rudabai, widow of the Vaghela chieftain Rana Veer Singh of Dandai Desh. Begada allows the completion of this five-story subterranean stepwell, retaining its mixed Hindu iconography and Islamic geometric carvings.",
    isKeyMilestone: true
  },
  {
    id: "evt-1500-dada-harir",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "1500 CE",
    numericYear: 1500,
    hijri: "906 AH",
    category: "Architectural",
    primaryCategory: "Architectural",
    title: "Construction of Dada Harir Stepwell",
    figures: ["Dhai Harir (Sultani)", "Mahmud Begada"],
    details: "Commissioned by Dhai Harir (Sultani), a senior lady-in-waiting of Mahmud Begada's zenana, featuring ornate Sanskrit and Arabic bilingual inscriptions in Ahmedabad.",
    isKeyMilestone: false
  },
  {
    id: "evt-1500-rani-sipri",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "c. 1500–1514 CE",
    numericYear: 1500,
    hijri: "",
    category: "Architectural",
    primaryCategory: "Architectural",
    title: "Patronage of Rani Sipri",
    figures: ["Rani Sipri (Asni)", "Mahmud Begada"],
    details: "Begada's Hindu consort, Rani Sipri (Asni), finances and oversees the construction of Rani Sipri's Mosque (Masjid-e-Nagina), celebrated for its intricate stone tracery and slender decorative minarets.",
    isKeyMilestone: false
  },
  {
    id: "evt-1507-coalition",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "1507–1508 CE",
    numericYear: 1507,
    hijri: "",
    category: "Military / Maritime",
    primaryCategory: "Maritime",
    title: "Formation of the Indian Ocean Coalition",
    figures: ["Mahmud Begada", "Sultan Qansuh al-Ghawri (Mamluk Sultanate)", "Zamorin of Calicut"],
    details: "Begada forms a naval alliance with the Mamluk Sultanate of Cairo (Sultan Qansuh al-Ghawri) and the Zamorin of Calicut to expel the Portuguese fleet from the western Indian waters.",
    isKeyMilestone: true
  },
  {
    id: "evt-1508-chaul",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "March 1508 CE",
    numericYear: 1508,
    hijri: "",
    category: "Military / Maritime",
    primaryCategory: "Maritime",
    title: "The Battle of Chaul",
    figures: ["Malik Ayyaz (Governor of Diu)", "Amir Husain Al-Kurdi (Mamluk admiral)", "Lourenço de Almeida"],
    details: "A joint fleet under Malik Ayyaz (Governor of Diu) and Amir Husain Al-Kurdi (Mamluk admiral) engages the Portuguese off the port of Chaul. Portuguese commander Lourenço de Almeida (son of the Viceroy) is killed; his flagship is sunk in the first major Asian naval victory over European vessels.",
    isKeyMilestone: true
  },
  {
    id: "evt-1509-diu",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "Feb 3, 1509 CE",
    numericYear: 1509,
    hijri: "",
    category: "Military / Maritime",
    primaryCategory: "Maritime",
    title: "The Battle of Diu",
    figures: ["Francisco de Almeida", "Malik Ayyaz", "Mahmud Begada"],
    details: "Portuguese Viceroy Francisco de Almeida sails to Diu seeking vengeance. He inflicts a crushing defeat on the joint Muslim fleet in Diu channel. Begada signs a tactical peace treaty, surrendering prisoners and granting commercial trading rights while refusing to allow a Portuguese stone fortress on land.",
    isKeyMilestone: true
  },
  {
    id: "evt-1511-death-begada",
    phaseId: 3,
    phaseTitle: "Phase 3: The Golden Age – Mahmud Begada (1458 – 1511 CE)",
    phaseShort: "Phase 3: The Golden Age",
    year: "Nov 23, 1511 CE",
    numericYear: 1511,
    hijri: "2 Ramadan 917 AH",
    category: "Dynastic",
    primaryCategory: "Dynastic",
    title: "Death of Mahmud Begada",
    figures: ["Mahmud Begada", "Shaikh Ahmad Khattu"],
    details: "After ruling for 53 years, Begada dies at age 66. He is laid to rest at the feet of his spiritual mentor Shaikh Ahmad Khattu in the mausoleum complex at Sarkhej Roza.",
    isKeyMilestone: true
  },

  // ==========================================
  // PHASE 4: THE TRAGIC CLIMAX & DOWNFALL (1511 – 1537 / 1573 CE)
  // ==========================================
  {
    id: "evt-1511-muzaffar2",
    phaseId: 4,
    phaseTitle: "Phase 4: The Tragic Climax & Downfall (1511 – 1537 / 1573 CE)",
    phaseShort: "Phase 4: Tragic Climax",
    year: "Nov 1511 CE",
    numericYear: 1511,
    hijri: "",
    category: "Dynastic",
    primaryCategory: "Dynastic",
    title: "Accession of Muzaffar Shah II (The Clement)",
    figures: ["Khalil Khan (Sultan Shams-ud-din Muzaffar Shah II)", "Mahmud Begada", "Rani Rani (Bibi Rani)"],
    details: "Khalil Khan (son of Begada and Rani Rani/Bibi Rani) ascends the throne as Shams-ud-din Muzaffar Shah II.",
    isKeyMilestone: false
  },
  {
    id: "evt-1514-malwa",
    phaseId: 4,
    phaseTitle: "Phase 4: The Tragic Climax & Downfall (1511 – 1537 / 1573 CE)",
    phaseShort: "Phase 4: Tragic Climax",
    year: "1514–1518 CE",
    numericYear: 1514,
    hijri: "",
    category: "Military",
    primaryCategory: "Military",
    title: "Malwa Campaigns & Recapture of Mandu",
    figures: ["Muzaffar Shah II", "Sultan Mahmud Khalji II", "Medini Rai"],
    details: "Muzaffar II marches into Malwa to rescue Sultan Mahmud Khalji II from the dominance of his Rajput prime minister, Medini Rai. In 1518, Gujarat troops storm the fortress of Mandu, restoring Khalji to the throne.",
    isKeyMilestone: false
  },
  {
    id: "evt-1519-sanga",
    phaseId: 4,
    phaseTitle: "Phase 4: The Tragic Climax & Downfall (1511 – 1537 / 1573 CE)",
    phaseShort: "Phase 4: Tragic Climax",
    year: "1519–1521 CE",
    numericYear: 1519,
    hijri: "",
    category: "Military",
    primaryCategory: "Military",
    title: "Clashes with Rana Sanga of Mewar",
    figures: ["Muzaffar Shah II", "Rana Sanga of Mewar", "Malik Ayyaz"],
    details: "Rana Sanga intervenes in Idar and sacks parts of northern Gujarat. Muzaffar II mounts counter-campaigns under Malik Ayyaz to push Mewar back, culminating in a tense standoff at Mandsaur.",
    isKeyMilestone: false
  },
  {
    id: "evt-1526-death-muzaffar2",
    phaseId: 4,
    phaseTitle: "Phase 4: The Tragic Climax & Downfall (1511 – 1537 / 1573 CE)",
    phaseShort: "Phase 4: Tragic Climax",
    year: "April 1526 CE",
    numericYear: 1526,
    hijri: "Jumada II 932 AH",
    category: "Dynastic",
    primaryCategory: "Dynastic",
    title: "Death of Muzaffar Shah II",
    figures: ["Muzaffar Shah II"],
    details: "Muzaffar Shah II dies peacefully at Ahmedabad. His passing ignites a succession struggle among his sons.",
    isKeyMilestone: false
  },
  {
    id: "evt-1526-sikandar",
    phaseId: 4,
    phaseTitle: "Phase 4: The Tragic Climax & Downfall (1511 – 1537 / 1573 CE)",
    phaseShort: "Phase 4: Tragic Climax",
    year: "May–July 1526 CE",
    numericYear: 1526,
    hijri: "",
    category: "Dynastic Coup",
    primaryCategory: "Dynastic",
    title: "Murder of Sikandar Shah & Coup of Imad-ul-Mulk",
    figures: ["Sikandar Shah", "Imad-ul-Mulk Khushqadam", "Nasir Khan (Mahmud Shah II)"],
    details: "The eldest son, Sikandar Shah, rules for two months before being murdered in his bed at Champaner by minister Imad-ul-Mulk Khushqadam. Imad sets up an infant prince, Nasir Khan (Mahmud Shah II), as a puppet monarch.",
    isKeyMilestone: false
  },
  {
    id: "evt-1526-ascension-bahadur",
    phaseId: 4,
    phaseTitle: "Phase 4: The Tragic Climax & Downfall (1511 – 1537 / 1573 CE)",
    phaseShort: "Phase 4: Tragic Climax",
    year: "July 1526 CE",
    numericYear: 1526,
    hijri: "",
    category: "Dynastic",
    primaryCategory: "Dynastic",
    title: "Ascension of Bahadur Shah",
    figures: ["Sultan Bahadur Shah (Bahadur Khan)", "Imad-ul-Mulk", "Ibrahim Lodi"],
    details: "Another son, Bahadur Khan—who had fled Gujarat following disputes with his father and spent years wandering the courts of Mewar, Delhi (Ibrahim Lodi), and Jaunpur—returns with an army, executes Imad-ul-Mulk, and takes the throne as Sultan Bahadur Shah.",
    isKeyMilestone: true
  },
  {
    id: "evt-1526-babur",
    phaseId: 4,
    phaseTitle: "Phase 4: The Tragic Climax & Downfall (1511 – 1537 / 1573 CE)",
    phaseShort: "Phase 4: Tragic Climax",
    year: "1526 CE",
    numericYear: 1526,
    hijri: "",
    category: "Geopolitical",
    primaryCategory: "Geopolitical",
    title: "Babur Founds the Mughal Empire",
    figures: ["Babur", "Bahadur Shah"],
    details: "Babur crushes the Delhi Sultanate at the First Battle of Panipat. Afghan refugees and dissident nobles flock to Gujarat, where Bahadur welcomes them, sowing future hostility with the Mughals.",
    isKeyMilestone: true
  },
  {
    id: "evt-1531-malwa",
    phaseId: 4,
    phaseTitle: "Phase 4: The Tragic Climax & Downfall (1511 – 1537 / 1573 CE)",
    phaseShort: "Phase 4: Tragic Climax",
    year: "1531 CE",
    numericYear: 1531,
    hijri: "",
    category: "Military",
    primaryCategory: "Military",
    title: "Annexation of Malwa",
    figures: ["Bahadur Shah", "Mahmud Khalji II"],
    details: "Frustrated by the treachery of Mahmud Khalji II, Bahadur invades Malwa, captures the mountain citadel of Mandu, and formally incorporates the Malwa Sultanate into the Gujarat crown.",
    isKeyMilestone: false
  },
  {
    id: "evt-1531-diu-defense",
    phaseId: 4,
    phaseTitle: "Phase 4: The Tragic Climax & Downfall (1511 – 1537 / 1573 CE)",
    phaseShort: "Phase 4: Tragic Climax",
    year: "Feb 1531 CE",
    numericYear: 1531,
    hijri: "",
    category: "Military / Maritime",
    primaryCategory: "Maritime",
    title: "Defense of Diu against Nuno da Cunha",
    figures: ["Nuno da Cunha", "Malik Ishaq", "Mustafa Bayram (Rumi Khan)"],
    details: "Portuguese Governor Nuno da Cunha sails a massive fleet of over 400 vessels to seize Diu. The garrison, commanded by Malik Ishaq and Ottoman artillery master Mustafa Bayram (Rumi Khan), bombards the Portuguese armada, forcing an embarrassing retreat.",
    isKeyMilestone: true
  },
  {
    id: "evt-1534-chittorgarh",
    phaseId: 4,
    phaseTitle: "Phase 4: The Tragic Climax & Downfall (1511 – 1537 / 1573 CE)",
    phaseShort: "Phase 4: Tragic Climax",
    year: "1534–1535 CE",
    numericYear: 1534,
    hijri: "",
    category: "Military",
    primaryCategory: "Military",
    title: "Siege and Sack of Chittorgarh",
    figures: ["Bahadur Shah", "Rani Karnavati", "Emperor Humayun", "Rumi Khan"],
    details: "Bahadur besieges the fortress of Chittorgarh using Ottoman siege cannons. Rani Karnavati sends a ceremonial rakhi to Mughal Emperor Humayun pleading for aid; Humayun hesitates, Chittor falls, and the Rajput women commit Jauhar.",
    isKeyMilestone: true
  },
  {
    id: "evt-1534-bassein",
    phaseId: 4,
    phaseTitle: "Phase 4: The Tragic Climax & Downfall (1511 – 1537 / 1573 CE)",
    phaseShort: "Phase 4: Tragic Climax",
    year: "1534 CE (Dec 23)",
    numericYear: 1534,
    hijri: "",
    category: "Geopolitical / Treaty",
    primaryCategory: "Treaty",
    title: "Treaty of Bassein",
    figures: ["Bahadur Shah", "Emperor Humayun", "Portuguese Crown"],
    details: "Squeezed between Humayun's advancing army and the sea, Bahadur signs an emergency pact aboard the galleon São Mateus, ceding the territory of Bassein (Vasai), along with its islands and maritime revenues, to the Portuguese Crown.",
    isKeyMilestone: true
  },
  {
    id: "evt-1535-humayun",
    phaseId: 4,
    phaseTitle: "Phase 4: The Tragic Climax & Downfall (1511 – 1537 / 1573 CE)",
    phaseShort: "Phase 4: Tragic Climax",
    year: "1535 CE",
    numericYear: 1535,
    hijri: "",
    category: "Military",
    primaryCategory: "Military",
    title: "Humayun's Invasion of Gujarat",
    figures: ["Emperor Humayun", "Bahadur Shah", "Rumi Khan"],
    details: "Humayun invades Malwa and Gujarat. Bahadur is routed at the Battle of Mandsaur after artillery chief Rumi Khan deserts to the Mughal camp. Humayun sacks Champaner's citadel and captures the royal treasuries. Bahadur flees to Cambay and Diu.",
    isKeyMilestone: true
  },
  {
    id: "evt-1535-diu-concession",
    phaseId: 4,
    phaseTitle: "Phase 4: The Tragic Climax & Downfall (1511 – 1537 / 1573 CE)",
    phaseShort: "Phase 4: Tragic Climax",
    year: "Oct 1535 CE",
    numericYear: 1535,
    hijri: "",
    category: "Geopolitical / Treaty",
    primaryCategory: "Treaty",
    title: "The Diu Concession",
    figures: ["Bahadur Shah", "Nuno da Cunha", "Emperor Humayun"],
    details: "In complete desperation at Diu, Bahadur signs a second agreement with Nuno da Cunha granting the Portuguese permission to construct a stone fortress on the island of Diu in return for naval and mercenary support against Humayun.",
    isKeyMilestone: true
  },
  {
    id: "evt-1536-recovery",
    phaseId: 4,
    phaseTitle: "Phase 4: The Tragic Climax & Downfall (1511 – 1537 / 1573 CE)",
    phaseShort: "Phase 4: Tragic Climax",
    year: "1536 CE",
    numericYear: 1536,
    hijri: "",
    category: "Military",
    primaryCategory: "Military",
    title: "Humayun Retreats; Gujarat Recovered",
    figures: ["Sher Shah Suri", "Emperor Humayun", "Bahadur Shah"],
    details: "Rebellions in Bihar and Bengal led by Sher Shah Suri force Humayun to withdraw his garrison troops from Ahmedabad and Champaner. Bahadur swiftly reoccupies Gujarat, but finds the newly constructed Portuguese fort at Diu an intolerable foreign base on his home soil.",
    isKeyMilestone: false
  },
  {
    id: "evt-1537-drowning",
    phaseId: 4,
    phaseTitle: "Phase 4: The Tragic Climax & Downfall (1511 – 1537 / 1573 CE)",
    phaseShort: "Phase 4: Tragic Climax",
    year: "Feb 13, 1537 CE",
    numericYear: 1537,
    hijri: "3 Ramadan 943 AH",
    category: "Assassination",
    primaryCategory: "Assassination",
    title: "Betrayal and Drowning of Bahadur Shah off Diu",
    figures: ["Bahadur Shah", "Nuno da Cunha"],
    details: "Bahadur attempts to resolve the fort dispute by visiting Governor Nuno da Cunha aboard his flagship in Diu harbor with a minimal escort. Sensing a trap, an altercation breaks out on the deck. Bahadur leaps into the sea to swim toward his royal barge, but is clubbed with an oar/halberd by a Portuguese sailor and drowns. His body sinks into the Arabian Sea and is never recovered.",
    isKeyMilestone: true
  },

  // ==========================================
  // EPILOGUE: THE SLOW EXTINCTION (1537 – 1573 / 1592 CE)
  // ==========================================
  {
    id: "evt-1537-mahmud3",
    phaseId: 5,
    phaseTitle: "Epilogue: The Slow Extinction (1537 – 1573 / 1592 CE)",
    phaseShort: "Epilogue: Extinction",
    year: "1537–1554 CE",
    numericYear: 1537,
    hijri: "",
    category: "Dynastic / Collapse",
    primaryCategory: "Dynastic",
    title: "Reign of Mahmud Shah III",
    figures: ["Mahmud Shah III", "Dadu", "Imad-ul-Mulk", "Asaf Khan", "Burhan"],
    details: "Bahadur's young nephew Mahmud III is enthroned. The Sultanate fragments into autonomous fiefdoms ruled by self-serving nobles (such as Dadu, Imad-ul-Mulk, and Asaf Khan). Mahmud III is murdered by his servant Burhan in 1554.",
    isKeyMilestone: false
  },
  {
    id: "evt-1554-partition",
    phaseId: 5,
    phaseTitle: "Epilogue: The Slow Extinction (1537 – 1573 / 1592 CE)",
    phaseShort: "Epilogue: Extinction",
    year: "1554–1572 CE",
    numericYear: 1554,
    hijri: "",
    category: "Political Fragmentation",
    primaryCategory: "Political",
    title: "The Partition of Gujarat",
    figures: ["Ahmad Shah III", "Muzaffar Shah III", "Itimad Khan", "Emperor Akbar"],
    details: "Ahmad Shah III and later Muzaffar Shah III serve as hollow figureheads. Prime Minister Itimad Khan and rival factions divide the provinces among themselves. Itimad Khan secretly invites Mughal Emperor Akbar to invade and restore order.",
    isKeyMilestone: false
  },
  {
    id: "evt-1572-akbar",
    phaseId: 5,
    phaseTitle: "Epilogue: The Slow Extinction (1537 – 1573 / 1592 CE)",
    phaseShort: "Epilogue: Extinction",
    year: "1572–1573 CE",
    numericYear: 1572,
    hijri: "",
    category: "Geopolitical Annexation",
    primaryCategory: "Geopolitical",
    title: "Akbar Annexes Gujarat",
    figures: ["Emperor Akbar", "Muzaffar Shah III", "Itimad Khan"],
    details: "Akbar marches into Ahmedabad in November 1572, accepts the surrender of the Gujarat nobility, takes possession of the coastal ports, and incorporates Gujarat as a province (Subah) of the Mughal Empire.",
    isKeyMilestone: true
  },
  {
    id: "evt-1583-final-stand",
    phaseId: 5,
    phaseTitle: "Epilogue: The Slow Extinction (1537 – 1573 / 1592 CE)",
    phaseShort: "Epilogue: Extinction",
    year: "1583–1592 CE",
    numericYear: 1583,
    hijri: "",
    category: "Dynastic Finale",
    primaryCategory: "Dynastic",
    title: "The Last Stand of Muzaffar Shah III",
    figures: ["Muzaffar Shah III", "Mughal Empire"],
    details: "The fugitive Muzaffar Shah III escapes Mughal custody and leads a localized insurgency in Kathiawar. Defeated at the Battle of Bhuchar Mori (1591), he flees to Kutch, is betrayed to the Mughals, and commits suicide by slitting his throat with a razor in 1592, ending the Muzaffarid bloodline.",
    isKeyMilestone: true
  }
];

// Phase metadata dictionary
const GUJARAT_PHASES = [
  {
    id: 1,
    title: "Phase 1: The Rise & The Founder",
    span: "1391 – 1442 CE",
    summary: "Establishment of regional autonomy following Delhi's collapse, foundation of Ahmedabad by Ahmad Shah I, and the architectural consolidation of the realm."
  },
  {
    id: 2,
    title: "Phase 2: Palace Intrigue & Survival",
    span: "1442 – 1458 CE",
    summary: "Succession crises, Mewar and Malwa clashes, the spiritual refuge of young Fateh Khan under Hazrat Shah Alam, and the 27-day coup before Begada's coronation."
  },
  {
    id: 3,
    title: "Phase 3: The Golden Age – Mahmud Begada",
    span: "1458 – 1511 CE",
    summary: "The 53-year zenith: capture of Junagadh and Pavagadh ('Be-Gadh'), foundation of Champaner, stepwell architecture, and historic Indian Ocean naval wars against the Portuguese."
  },
  {
    id: 4,
    title: "Phase 4: The Tragic Climax & Downfall",
    span: "1511 – 1537 / 1573 CE",
    summary: "Muzaffar II's campaigns, Bahadur Shah's conquests, existential clashes with Humayun's Mughal forces, Portuguese concessions at Bassein and Diu, and Bahadur's tragic assassination."
  },
  {
    id: 5,
    title: "Epilogue: The Slow Extinction",
    span: "1537 – 1573 / 1592 CE",
    summary: "Fragmented aristocratic anarchy, Mahmud III's murder, Emperor Akbar's imperial annexation in 1572, and the suicide of Muzaffar Shah III in 1592."
  }
];

// Export to browser window and node environment
if (typeof window !== "undefined") {
  window.GUJARAT_SULTANATE_DATA = GUJARAT_SULTANATE_DATA;
  window.GUJARAT_PHASES = GUJARAT_PHASES;
}
if (typeof module !== "undefined" && module.exports) {
  module.exports = { GUJARAT_SULTANATE_DATA, GUJARAT_PHASES };
}
